import {
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Tooltip } from "@radix-ui/react-tooltip";
import { Mouse } from "lucide-react";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Footer from "./_components/layout/footer";
import Header from "./_components/layout/header";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin", "vietnamese"],
  adjustFontFallback: true,
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Artix",
  description: "Generated by create next app",
  applicationName: "Artix",
  authors: [
    {
      name: "tiendatcactus",
      url: "https://github.com/TienDatCactus/artix",
    },
  ],
  generator: "Next.js",
  keywords: ["Artix", "3D Printing", "Design"],
  referrer: "origin-when-cross-origin",
  colorScheme: "dark",
  viewport: "width=device-width, initial-scale=1",
  creator: "tiendatcactus",
  publisher: "Artix",
  robots: {
    index: true,
    follow: true,
    "max-image-preview": "large",
    "max-video-preview": "-1",
    noarchive: false,
    nosnippet: false,
    noimageindex: false,
  },

  openGraph: {
    title: "Artix",
    description:
      "ARTIX Studio - Đơn vị sản xuất Art toy, cung cấp dịch vụ thiết kế và in 3D theo yêu cầu.",
    url: "https://artix.vn",
    siteName: "Artix",
    images: [
      {
        url: "/images/artix_bg.jpg",
        width: 1200,
        height: 630,
        alt: "Artix Studio",
        type: "image/jpeg",
      },
      {
        url: "/images/artix_ic.jpg",
        width: 600,
        height: 630,
        alt: "Artix Studio",
        type: "image/jpeg",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Artix",
    description:
      "ARTIX Studio - Đơn vị sản xuất Art toy, cung cấp dịch vụ thiết kế và in 3D theo yêu cầu.",
    images: [
      {
        url: "/images/artix_bg.jpg",
        width: 1200,
        height: 630,
        alt: "Artix Studio",
        type: "image/jpeg",
      },
      {
        url: "/images/artix_ic.jpg",
        width: 600,
        height: 630,
        alt: "Artix Studio",
        type: "image/jpeg",
      },
    ],
  },

  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: "/images/favicon.ico",
    apple: "/images/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <html lang="en">
        <body className={`${spaceGrotesk.variable} antialiased relative`}>
          <Header />
          <main className="bg-main-primary ">{children}</main>
          <Footer />
          <Tooltip>
            <TooltipTrigger className="fixed flex items-center justify-center bottom-6 right-6 z-20 hover:bg-true-primary/80 text-white rounded-full cursor-pointer size-14 group">
              <a href="#hero" className="block">
                <Mouse className="text-true-primary group-hover:text-white size-8 " />
              </a>
            </TooltipTrigger>
            <TooltipContent>Cuộn lên đầu</TooltipContent>
          </Tooltip>
        </body>
      </html>
    </TooltipProvider>
  );
}
