import {
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Tooltip } from "@radix-ui/react-tooltip";
import { Mouse } from "lucide-react";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Footer from "./_components/layout/footer";
import Header from "./_components/layout/header";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin", "vietnamese"],
  adjustFontFallback: true,
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Artix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <html lang="en">
        <body className={`${spaceGrotesk.variable} antialiased relative`}>
          <Header />
          <main className="bg-main-primary ">{children}</main>
          <Footer />
          <Tooltip>
            <TooltipTrigger className="fixed flex items-center justify-center lg:bottom-6 lg:right-6 z-20 hover:bg-true-primary/80 text-white rounded-full cursor-pointer lg:size-14 group">
              <a href="#hero" className="hidden lg:block">
                <Mouse className="text-true-primary group-hover:text-white lg:size-8 " />
              </a>
            </TooltipTrigger>
            <TooltipContent>Cuộn lên đầu</TooltipContent>
          </Tooltip>
        </body>
      </html>
    </TooltipProvider>
  );
}
